// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=none"
// @generated from file bidi.proto (package aiserver.v1, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file bidi.proto.
 */
export const file_bidi: GenFile =
	/*@__PURE__*/
	fileDesc(
		"CgpiaWRpLnByb3RvEgthaXNlcnZlci52MSIjCg1CaWRpUmVxdWVzdElkEhIKCnJlcXVlc3RfaWQYASABKAkifAoRQmlkaUFwcGVuZFJlcXVlc3QSDAoEZGF0YRgBIAEoCRIuCgpyZXF1ZXN0X2lkGAIgASgLMhouYWlzZXJ2ZXIudjEuQmlkaVJlcXVlc3RJZBIUCgxhcHBlbmRfc2Vxbm8YAyABKAQSEwoLZGF0YV9iaW5hcnkYBCABKAwiFAoSQmlkaUFwcGVuZFJlc3BvbnNlIlgKD0JpZGlQb2xsUmVxdWVzdBIuCgpyZXF1ZXN0X2lkGAEgASgLMhouYWlzZXJ2ZXIudjEuQmlkaVJlcXVlc3RJZBIVCg1zdGFydF9yZXF1ZXN0GAIgASgIIjwKEEJpZGlQb2xsUmVzcG9uc2USDQoFc2Vxbm8YASABKAQSDAoEZGF0YRgCIAEoCRILCgNlb2YYAyABKAgyXAoLQmlkaVNlcnZpY2USTQoKQmlkaUFwcGVuZBIeLmFpc2VydmVyLnYxLkJpZGlBcHBlbmRSZXF1ZXN0Gh8uYWlzZXJ2ZXIudjEuQmlkaUFwcGVuZFJlc3BvbnNlYgZwcm90bzM",
	);

/**
 * Identifies one logical bidi request across the append/poll/SSE channels.
 *
 * @generated from message aiserver.v1.BidiRequestId
 */
export type BidiRequestId = Message<"aiserver.v1.BidiRequestId"> & {
	/**
	 * @generated from field: string request_id = 1;
	 */
	requestId: string;
};

/**
 * Describes the message aiserver.v1.BidiRequestId.
 * Use `create(BidiRequestIdSchema)` to create a new message.
 */
export const BidiRequestIdSchema: GenMessage<BidiRequestId> = /*@__PURE__*/ messageDesc(file_bidi, 0);

/**
 * Appends a client frame (AgentClientMessage bytes) to an open bidi request.
 *
 * @generated from message aiserver.v1.BidiAppendRequest
 */
export type BidiAppendRequest = Message<"aiserver.v1.BidiAppendRequest"> & {
	/**
	 * Legacy JSON-encoded payload slot (unused by omp; kept for wire parity).
	 *
	 * @generated from field: string data = 1;
	 */
	data: string;

	/**
	 * @generated from field: aiserver.v1.BidiRequestId request_id = 2;
	 */
	requestId?: BidiRequestId | undefined;

	/**
	 * Monotonic per-request sequence number for FIFO ordering on the server.
	 *
	 * @generated from field: uint64 append_seqno = 3;
	 */
	appendSeqno: bigint;

	/**
	 * Binary AgentClientMessage frame.
	 *
	 * @generated from field: bytes data_binary = 4;
	 */
	dataBinary: Uint8Array;
};

/**
 * Describes the message aiserver.v1.BidiAppendRequest.
 * Use `create(BidiAppendRequestSchema)` to create a new message.
 */
export const BidiAppendRequestSchema: GenMessage<BidiAppendRequest> = /*@__PURE__*/ messageDesc(file_bidi, 1);

/**
 * Response to a BidiAppend call. No fields are consumed by omp.
 *
 * @generated from message aiserver.v1.BidiAppendResponse
 */
export type BidiAppendResponse = Message<"aiserver.v1.BidiAppendResponse"> & {};

/**
 * Describes the message aiserver.v1.BidiAppendResponse.
 * Use `create(BidiAppendResponseSchema)` to create a new message.
 */
export const BidiAppendResponseSchema: GenMessage<BidiAppendResponse> = /*@__PURE__*/ messageDesc(file_bidi, 2);

/**
 * Polls buffered server frames for a bidi request (HTTP/1 receive fallback).
 *
 * @generated from message aiserver.v1.BidiPollRequest
 */
export type BidiPollRequest = Message<"aiserver.v1.BidiPollRequest"> & {
	/**
	 * @generated from field: aiserver.v1.BidiRequestId request_id = 1;
	 */
	requestId?: BidiRequestId | undefined;

	/**
	 * When true, (re)starts the server stream for this request id.
	 *
	 * @generated from field: bool start_request = 2;
	 */
	startRequest: boolean;
};

/**
 * Describes the message aiserver.v1.BidiPollRequest.
 * Use `create(BidiPollRequestSchema)` to create a new message.
 */
export const BidiPollRequestSchema: GenMessage<BidiPollRequest> = /*@__PURE__*/ messageDesc(file_bidi, 3);

/**
 * One polled server frame.
 *
 * @generated from message aiserver.v1.BidiPollResponse
 */
export type BidiPollResponse = Message<"aiserver.v1.BidiPollResponse"> & {
	/**
	 * @generated from field: uint64 seqno = 1;
	 */
	seqno: bigint;

	/**
	 * Server frame data (string in vendor wire, not bytes).
	 *
	 * @generated from field: string data = 2;
	 */
	data: string;

	/**
	 * @generated from field: bool eof = 3;
	 */
	eof: boolean;
};

/**
 * Describes the message aiserver.v1.BidiPollResponse.
 * Use `create(BidiPollResponseSchema)` to create a new message.
 */
export const BidiPollResponseSchema: GenMessage<BidiPollResponse> = /*@__PURE__*/ messageDesc(file_bidi, 4);

/**
 * Client->server frame append. Server frames are consumed via the
 * AgentService.RunSSE / RunPoll server-streaming methods (declared in the
 * hand-corrected transport descriptors), not through this service.
 *
 * @generated from service aiserver.v1.BidiService
 */
export const BidiService: GenService<{
	/**
	 * @generated from rpc aiserver.v1.BidiService.BidiAppend
	 */
	bidiAppend: {
		methodKind: "unary";
		input: typeof BidiAppendRequestSchema;
		output: typeof BidiAppendResponseSchema;
	};
}> = /*@__PURE__*/ serviceDesc(file_bidi, 0);
