// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=none"
// @generated from file server_config.proto (package aiserver.v1, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file server_config.proto.
 */
export const file_server_config: GenFile =
	/*@__PURE__*/
	fileDesc(
		"ChNzZXJ2ZXJfY29uZmlnLnByb3RvEgthaXNlcnZlci52MSI3Cg5BZ2VudFVybENvbmZpZxIRCglhZ2VudF91cmwYASABKAkSEgoKYWdlbnRuX3VybBgCIAEoCSIYChZHZXRTZXJ2ZXJDb25maWdSZXF1ZXN0IoABChdHZXRTZXJ2ZXJDb25maWdSZXNwb25zZRIuCgxodHRwMl9jb25maWcYByABKA4yGC5haXNlcnZlci52MS5IdHRwMkNvbmZpZxI1ChBhZ2VudF91cmxfY29uZmlnGBsgASgLMhsuYWlzZXJ2ZXIudjEuQWdlbnRVcmxDb25maWcqvwEKC0h0dHAyQ29uZmlnEhwKGEhUVFAyX0NPTkZJR19VTlNQRUNJRklFRBAAEiMKH0hUVFAyX0NPTkZJR19GT1JDRV9BTExfRElTQUJMRUQQARIiCh5IVFRQMl9DT05GSUdfRk9SQ0VfQUxMX0VOQUJMRUQQAhIkCiBIVFRQMl9DT05GSUdfRk9SQ0VfQklESV9ESVNBQkxFRBADEiMKH0hUVFAyX0NPTkZJR19GT1JDRV9CSURJX0VOQUJMRUQQBDJzChNTZXJ2ZXJDb25maWdTZXJ2aWNlElwKD0dldFNlcnZlckNvbmZpZxIjLmFpc2VydmVyLnYxLkdldFNlcnZlckNvbmZpZ1JlcXVlc3QaJC5haXNlcnZlci52MS5HZXRTZXJ2ZXJDb25maWdSZXNwb25zZWIGcHJvdG8z",
	);

/**
 * @generated from message aiserver.v1.AgentUrlConfig
 */
export type AgentUrlConfig = Message<"aiserver.v1.AgentUrlConfig"> & {
	/**
	 * @generated from field: string agent_url = 1;
	 */
	agentUrl: string;

	/**
	 * @generated from field: string agentn_url = 2;
	 */
	agentnUrl: string;
};

/**
 * Describes the message aiserver.v1.AgentUrlConfig.
 * Use `create(AgentUrlConfigSchema)` to create a new message.
 */
export const AgentUrlConfigSchema: GenMessage<AgentUrlConfig> = /*@__PURE__*/ messageDesc(file_server_config, 0);

/**
 * @generated from message aiserver.v1.GetServerConfigRequest
 */
export type GetServerConfigRequest = Message<"aiserver.v1.GetServerConfigRequest"> & {};

/**
 * Describes the message aiserver.v1.GetServerConfigRequest.
 * Use `create(GetServerConfigRequestSchema)` to create a new message.
 */
export const GetServerConfigRequestSchema: GenMessage<GetServerConfigRequest> =
	/*@__PURE__*/
	messageDesc(file_server_config, 1);

/**
 * @generated from message aiserver.v1.GetServerConfigResponse
 */
export type GetServerConfigResponse = Message<"aiserver.v1.GetServerConfigResponse"> & {
	/**
	 * Server-forced transport policy (bare enum on the wire, field 7).
	 *
	 * @generated from field: aiserver.v1.Http2Config http2_config = 7;
	 */
	http2Config: Http2Config;

	/**
	 * @generated from field: aiserver.v1.AgentUrlConfig agent_url_config = 27;
	 */
	agentUrlConfig?: AgentUrlConfig | undefined;
};

/**
 * Describes the message aiserver.v1.GetServerConfigResponse.
 * Use `create(GetServerConfigResponseSchema)` to create a new message.
 */
export const GetServerConfigResponseSchema: GenMessage<GetServerConfigResponse> =
	/*@__PURE__*/
	messageDesc(file_server_config, 2);

/**
 * Server-forced bidi/HTTP2 policy. UNSPECIFIED leaves the choice to the local
 * `providers.cursor.useHttp1ForAgent` preference.
 *
 * @generated from enum aiserver.v1.Http2Config
 */
export enum Http2Config {
	/**
	 * @generated from enum value: HTTP2_CONFIG_UNSPECIFIED = 0;
	 */
	UNSPECIFIED = 0,

	/**
	 * @generated from enum value: HTTP2_CONFIG_FORCE_ALL_DISABLED = 1;
	 */
	FORCE_ALL_DISABLED = 1,

	/**
	 * @generated from enum value: HTTP2_CONFIG_FORCE_ALL_ENABLED = 2;
	 */
	FORCE_ALL_ENABLED = 2,

	/**
	 * @generated from enum value: HTTP2_CONFIG_FORCE_BIDI_DISABLED = 3;
	 */
	FORCE_BIDI_DISABLED = 3,

	/**
	 * @generated from enum value: HTTP2_CONFIG_FORCE_BIDI_ENABLED = 4;
	 */
	FORCE_BIDI_ENABLED = 4,
}

/**
 * Describes the enum aiserver.v1.Http2Config.
 */
export const Http2ConfigSchema: GenEnum<Http2Config> = /*@__PURE__*/ enumDesc(file_server_config, 0);

/**
 * @generated from service aiserver.v1.ServerConfigService
 */
export const ServerConfigService: GenService<{
	/**
	 * @generated from rpc aiserver.v1.ServerConfigService.GetServerConfig
	 */
	getServerConfig: {
		methodKind: "unary";
		input: typeof GetServerConfigRequestSchema;
		output: typeof GetServerConfigResponseSchema;
	};
}> = /*@__PURE__*/ serviceDesc(file_server_config, 0);
